In [1]:
import numpy as np

In [17]:
t = np.arange(0,5, 0.5)

In [19]:
t

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
i = np.where(t == 3)[0]
i

array([6], dtype=int64)

In [41]:
for i in t:
        print(i)

0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5


In [26]:
len(t>3)

10

In [33]:
np.append(t, True)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 1. ])

In [38]:
a = [0 for x in t]
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [39]:
len(t)

10